### ISSUE TITLE
In Product Detail: Show Contributor's Role on list with Name & Share %

### ISSUE THREAD

**Issue by scottrepreneur** [MetaFactoryAI/mf-app#224]
Update view to show name and share % in the list. Currently just the name is showing.

**Comment by scottrepreneur** [comment]
This is a view thing, so I'll try to look into it next.

**Comment by META-DREAMER** [comment]
Should be showing correctly 
![CleanShot 2022-11-09 at 19 13 08](https://user-images.githubusercontent.com/7143583/200983605-1b74d071-a77d-4e59-9edc-44b2f9781d1d.png)
